"""
FinSight RAG Pipeline
----------------------
Embeds news documents using the InferenceEngine,
stores them in a FAISS flat index, and retrieves
top-k relevant chunks at query time.

- FAISS IndexFlatIP = inner product similarity (cosine after L2 norm)
- Embeddings generated by InferenceEngine (CUDA optimized path)
- Retrieval score (0-1) feeds into ConfidenceLedger
- Index persists to disk so we don't re-embed on every run
- Two retrieval modes: ticker-specific and global search
"""

import os
import pickle
import numpy as np
import faiss
from pathlib import Path
from dataclasses import dataclass

from core.inference_engine import InferenceEngine
from core.news_fetcher import NewsDocument


INDEX_DIR = Path(__file__).parent.parent / "faiss_index"


@dataclass
class RetrievalResult:
    document:  NewsDocument
    score:     float          # cosine similarity 0-1
    rank:      int

    def to_context_string(self) -> str:
        return (
            f"[Source {self.rank} | Relevance: {self.score:.2f}]\n"
            f"{self.document.to_context_string()}"
        )


class RAGPipeline:
    """
    FAISS-backed retrieval pipeline.

    Build phase : embed all documents → store in FAISS
    Query phase : embed query → retrieve top-k → return scored docs
    """

    def __init__(self, inference_engine: InferenceEngine):
        self.engine    = inference_engine
        self.index     = None
        self.documents: list[NewsDocument] = []
        self.dimension = 384   # all-MiniLM-L6-v2 output dim
        INDEX_DIR.mkdir(exist_ok=True)

    def _normalize(self, vectors: np.ndarray) -> np.ndarray:
        """
        L2-normalize vectors so inner product == cosine similarity.
        This is why we use IndexFlatIP instead of IndexFlatL2.
        """
        norms = np.linalg.norm(vectors, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1e-10, norms)  # avoid div by zero
        return vectors / norms

    def build(self, documents: list[NewsDocument]) -> None:
        """
        Embed all documents and build the FAISS index.
        Called once when new news is fetched.
        """
        if not documents:
            print("[RAGPipeline] No documents to index.")
            return

        print(f"[RAGPipeline] Embedding {len(documents)} documents...")

        texts = [doc.to_context_string() for doc in documents]

        # Embed in batches of 32 to avoid OOM on large corpora
        batch_size  = 32
        all_vectors = []

        for i in range(0, len(texts), batch_size):
            batch   = texts[i:i + batch_size]
            vectors = self.engine.embed(batch)
            all_vectors.append(vectors)

        embeddings = np.vstack(all_vectors).astype("float32")
        embeddings = self._normalize(embeddings)

        # Build FAISS flat index (exact search, best for <100k docs)
        self.index = faiss.IndexFlatIP(self.dimension)
        self.index.add(embeddings)
        self.documents = documents

        print(f"[RAGPipeline] Index built: {self.index.ntotal} vectors")
        self._save()

    def retrieve(
        self,
        query: str,
        ticker: str = None,
        top_k: int = 5,
    ) -> list[RetrievalResult]:
        """
        Retrieve top-k most relevant documents for a query.
        Optionally filter by ticker for more focused context.

        Returns scored RetrievalResult objects.
        The top result's score is used by ConfidenceLedger.
        """
        if self.index is None or self.index.ntotal == 0:
            print("[RAGPipeline] Index empty. Call build() first.")
            return []

        # Embed query
        query_vec = self.engine.embed([query]).astype("float32")
        query_vec = self._normalize(query_vec)

        # Search — retrieve more than top_k if filtering by ticker
        search_k = top_k * 4 if ticker else top_k
        search_k = min(search_k, self.index.ntotal)

        scores, indices = self.index.search(query_vec, search_k)
        scores   = scores[0]
        indices  = indices[0]

        results = []
        rank    = 1

        for score, idx in zip(scores, indices):
            if idx < 0 or idx >= len(self.documents):
                continue

            doc = self.documents[idx]

            # Filter by ticker if specified
            if ticker and doc.ticker not in (ticker, "MARKET"):
                continue

            results.append(RetrievalResult(
                document=doc,
                score=float(score),
                rank=rank,
            ))
            rank += 1

            if len(results) >= top_k:
                break

        return results

    def retrieve_context_string(
        self,
        query: str,
        ticker: str = None,
        top_k: int = 5,
    ) -> tuple[str, float]:
        """
        Convenience method used by the trading agent.
        Returns (formatted_context, top_retrieval_score).
        top_retrieval_score feeds into ConfidenceLedger.
        """
        results = self.retrieve(query, ticker, top_k)

        if not results:
            return "No relevant news context found.", 0.0

        context_parts = [r.to_context_string() for r in results]
        context       = "\n\n---\n\n".join(context_parts)
        top_score     = results[0].score

        return context, top_score

    def _save(self) -> None:
        INDEX_DIR.mkdir(parents=True, exist_ok=True)
        faiss.write_index(self.index, str(INDEX_DIR / "index.faiss"))
        with open(INDEX_DIR / "documents.pkl", "wb") as f:
            pickle.dump(self.documents, f)
        print(f"[RAGPipeline] Index saved to {INDEX_DIR}/")

    def load(self) -> bool:
        """
        Load existing index from disk.
        Returns True if successful, False if no index exists.
        """
        index_path = INDEX_DIR / "index.faiss"
        docs_path  = INDEX_DIR / "documents.pkl"

        if not index_path.exists() or not docs_path.exists():
            return False

        self.index = faiss.read_index(str(index_path))
        with open(docs_path, "rb") as f:
            self.documents = pickle.load(f)

        print(f"[RAGPipeline] Loaded index: {self.index.ntotal} vectors, "
              f"{len(self.documents)} documents")
        return True

    @property
    def is_ready(self) -> bool:
        return self.index is not None and self.index.ntotal > 0